### ISSUE TITLE
ACT-R folder not found

### ISSUE THREAD

**Issue by justingeeslin** [db30/act-r-container#6]
Running the container in the Docker app for MacOS (12.7), I get a folder not found error looking for ACT-R.

<img width="805" alt="Screen Shot 2024-09-18 at 12 44 10 PM" src="https://github.com/user-attachments/assets/b5ba3b36-9225-4b15-82a5-f60fef12bbf2">

I think #5 helps, but the issue persists.

**Comment by justingeeslin** [comment]
#5  and #7  resolved this issue for me.

**Comment by db30** [comment]
The move is important because the actr7.x/tutorial directory is intended to be a volume outside of the container so that the files persist between uses since it's unlikely one would complete the tutorial in one setting.

I'm assuming that you got that issue because you didn't include the volume specification when running the container.  From the command line it would be with this parameter when running it (which would put it in an act-r-tutorial directory of your home directory):

-v ~/act-r-tutorial:/home/actr/actr7.x/tutorial

From the docker desktop interface you'd have to set that in the optional settings when you ran it.

If you did specify the volume, then I'd need more information to look into that further.

**Comment by db30** [comment]
The docker file has been updated to use the main ACT-R version which has gone through some basic testing and works.
